name: "OZ - Marketplace"
main: de.omegazirkel.risingworld.Marketplace
version: 0.3.2
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Player markets with partial trades, wanted listings, Wallet settlement, and Mail delivery"
license: N/A
website: https://api.github.com/repos/Devidian/rw-plugin-oz-marketplace/releases/latest
loadorder: 0
